= Documentation IGraph

WARNING: Cette documentation ainsi que l'interface et suscptible de changer

NOTE: Cette interface à été conçu sur base Ncurses

== Introduction

=== L'interface IGraph

L'interface IGraph permet de mettre en place différente méthodes qui seront communes
aux autres librairies graphiques. +
Par exemple, la méthode SetSprite() permettra de définir un image pour chaque lib graphique: +

* Ncurses créera un caractère pour un personnage
* SFML chargera une image pour un personnage

== Les méthodes

=== void createMap()

Créé le plateau de jeu.

=== void Game()

Méthode qui fera office de "refresh" pour jouer la partie et chargera en boucle les besoins du jeu

=== void SetSprite()

Met un sprite sur le screen (pour la ncurses juste un symbole avec de la couleur)

=== void UnsetSprite()

Inverse de SetSprite()

=== void Animation()

Cette méthode ce charge de l'animation des sprites


TIP: Référence pour la rédaction de la doc : +
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
