##
## Makefile for arcade in /home/huguet_t/Documents/Rendu/cpp_arcade/menu
## 
## Made by 
## Login   <thomas.huguet@epitech.eu>
## 
## Started on  Wed Apr  5 13:21:07 2017 
## Last update Wed Apr  5 13:22:28 2017 
##

all:
		make -C ncurses/
		make -C sfml/

clean:
		make clean -C ncurses/
		make clean -C sfml/

fclean:	
		make fclean -C ncurses/
		make fclean -C sfml/

re:		fclean all
